#
# AM623x Kisan System B/D Character Device Drivers
#
obj-$(CONFIG_KISAN_AM623x_COMMON)			+= kisan_common.o
obj-$(CONFIG_KISAN_AM623x_GPIO_INTR)		+= kisan_gpio_intr.o
obj-$(CONFIG_KISAN_AM623x_GPIO_HANDLER)		+= kisan_gpio_handler.o
obj-$(CONFIG_KISAN_AM623x_BOARD_S1P)		+= kisan_board_s1p.o
obj-$(CONFIG_KISAN_AM623x_USB_NOTIFIER)		+= kisan_usb_notifier.o